services:
  mysql_container:
    container_name: mysql_container
    hostname: mysql_container
    image: mysql:8
    restart: always
    volumes:
      - ./mysql_container:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      TZ: America/Sao_Paulo
