services:
  mysql_container:
    env_file:
      - .env
    container_name: mysql_container
    hostname: mysql_container
    image: mysql:8
    restart: always
    volumes:
      - ./mysql_container:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo
